# Generated by Django 4.1.1 on 2022-09-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('max_score', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=20)),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.subjects')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='none', max_length=10)),
                ('track_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.tracks')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('student_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='college.students')),
                ('subject_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='college.subjects')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
