# Generated by Django 4.1.1 on 2022-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], default='none', max_length=10),
        ),
    ]
