# Generated by Django 4.1.1 on 2022-09-21 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='track_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='college.tracks'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='subject_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='college.subjects'),
        ),
    ]
