# Generated by Django 4.1.1 on 2022-09-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_exam_date_alter_students_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], default='other', max_length=10),
        ),
    ]
